/**
 * [INPUT]: The active server locale.
 * [OUTPUT]: Five-language assistance and explicit upgrade messages without task content.
 * [POS]: Shared main/worker copy for the assistance boundary.
 * [PROTOCOL]: Update this header when making changes, then check README.md.
 */
import { serverLocale } from './server'
const catalogs = {
  zh: { notesRewritten: '已重写笔记', notesChanged: '笔记已编辑，无法撤销重写。新内容已保留。', inactive: '请先将任务恢复为未完成并解除归档。', guidanceChanged: '推进说明已更新，请重新查看。', contextChanged: '任务或日期已变化，请重新查看预览。', saved: '已更新推进说明', cleared: '已清除推进说明', appliedAndMoved: '已更新推进说明和安排', consentRequired: '生成前，请同意向所选服务发送任务正文、执行摘要和求助内容。', upgradeTitle: '升级工作区格式', upgradePrepare: '此工作区使用旧格式。先创建并校验保护副本，再确认升级。', upgradeConfirm: '保护副本已校验。确认后将使用新库替换活动工作区，原数据保留在副本中。', prepare: '创建保护副本', confirm: '确认升级', cancel: '退出并保留原库' },
  en: { notesRewritten: 'Notes rewritten', notesChanged: 'Notes have been edited. The rewrite cannot be undone; your changes are kept.', inactive: 'Reopen and unarchive this task first.', guidanceChanged: 'The guidance changed. Review it again.', contextChanged: 'The task or date changed. Review the preview again.', saved: 'Guidance updated', cleared: 'Guidance cleared', appliedAndMoved: 'Guidance and schedule updated', consentRequired: 'Before generating, allow the selected service to receive task text, execution facts and your help request.', upgradeTitle: 'Upgrade workspace format', upgradePrepare: 'This workspace uses an older format. Create and verify a protective copy before confirming the upgrade.', upgradeConfirm: 'The protective copy is verified. Confirmation replaces the active workspace with a new database. Your original data remains in the copy.', prepare: 'Create protective copy', confirm: 'Confirm upgrade', cancel: 'Quit and keep original' },
  ja: { notesRewritten: 'メモを書き直しました', notesChanged: 'メモが編集されています。書き直しは取り消せません。変更は保持されます。', inactive: 'タスクを未完了に戻し、アーカイブを解除してください。', guidanceChanged: '進め方が更新されました。再確認してください。', contextChanged: 'タスクまたは日付が変わりました。プレビューを再確認してください。', saved: '進め方を更新しました', cleared: '進め方を削除しました', appliedAndMoved: '進め方と予定を更新しました', consentRequired: '生成する前に、タスク本文、実行の要約、相談内容を選択したサービスへ送ることに同意してください。', upgradeTitle: 'ワークスペース形式を更新', upgradePrepare: '旧形式のワークスペースです。保護用コピーを作成して検証した後、更新を確認します。', upgradeConfirm: '保護用コピーを検証しました。確認すると新しいデータベースに置き換えます。元のデータはコピーに残ります。', prepare: '保護用コピーを作成', confirm: '更新を確認', cancel: '元のデータを保って終了' },
  es: { notesRewritten: 'Notas reescritas', notesChanged: 'Las notas se editaron. No se puede deshacer la reescritura; conservamos tus cambios.', inactive: 'Reabre la tarea y quita el archivo primero.', guidanceChanged: 'La guía cambió. Revísala de nuevo.', contextChanged: 'La tarea o la fecha cambió. Revisa la vista previa.', saved: 'Guía actualizada', cleared: 'Guía eliminada', appliedAndMoved: 'Guía y planificación actualizadas', consentRequired: 'Antes de generar, permite enviar el texto de la tarea, el resumen de ejecución y tu consulta al servicio elegido.', upgradeTitle: 'Actualizar el formato', upgradePrepare: 'Este espacio usa un formato anterior. Crea y verifica una copia de protección antes de confirmar.', upgradeConfirm: 'La copia de protección está verificada. La confirmación sustituye la base activa. Los datos originales quedan en la copia.', prepare: 'Crear copia de protección', confirm: 'Confirmar actualización', cancel: 'Salir y conservar el original' },
  fr: { notesRewritten: 'Notes réécrites', notesChanged: 'Les notes ont été modifiées. La réécriture ne peut pas être annulée ; vos changements sont conservés.', inactive: 'Rouvrez cette tâche et désarchivez-la avant de continuer.', guidanceChanged: 'La note a changé. Vérifiez-la à nouveau.', contextChanged: 'La tâche ou la date a changé. Vérifiez l’aperçu.', saved: 'Note de progression mise à jour', cleared: 'Note de progression effacée', appliedAndMoved: 'Note et planification mises à jour', consentRequired: 'Avant de générer, autorisez l’envoi du texte, du résumé d’exécution et de votre demande au service choisi.', upgradeTitle: 'Mettre à jour le format', upgradePrepare: 'Cet espace utilise un ancien format. Créez et vérifiez une copie de protection avant de confirmer.', upgradeConfirm: 'La copie de protection est vérifiée. La confirmation remplace la base active. Les données originales restent dans la copie.', prepare: 'Créer une copie de protection', confirm: 'Confirmer la mise à jour', cancel: 'Quitter et garder l’original' },
}
export function assistanceServerText() { return catalogs[serverLocale()] }
